"""Add avatar field to Employee model

Revision ID: 027f0c0ad424
Revises: 12dcb2d7124a
Create Date: 2024-10-15 15:07:15.486308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '027f0c0ad424'
down_revision = '12dcb2d7124a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'avatar')
    # ### end Alembic commands ###
