"""Sale to item id creation

Revision ID: 12dcb2d7124a
Revises: cca74d05ba60
Create Date: 2024-10-08 09:58:42.395996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '12dcb2d7124a'
down_revision = 'cca74d05ba60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sale', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='foreignkey')
    # ### end Alembic commands ###
