"""Add some models and fix

Revision ID: 422d5b10b456
Revises: 6c973b036011
Create Date: 2024-09-23 16:02:13.270334

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '422d5b10b456'
down_revision = '6c973b036011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('lead_product', sa.Uuid(), nullable=True),
    sa.Column('lead_quantity', sa.Integer(), nullable=True),
    sa.Column('lead_preferable_price_per_item', sa.Float(), nullable=True),
    sa.Column('lead_comments', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('lead_supporter_id', sa.Uuid(), nullable=True),
    sa.Column('lead_business_stage_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_priority', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businessstage',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_of_items', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('billing_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('billing_city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('billing_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('billing_country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('billing_zip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('shipping_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('shipping_city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('shipping_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('shipping_country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('shipping_zip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('receiver_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('receiver_phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('receiver_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('employee', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('sale')
    op.drop_table('businessstage')
    op.drop_table('stage')
    op.drop_table('lead')
    # ### end Alembic commands ###
