"""Item add supplier

Revision ID: 55cd88f727e3
Revises: 84f3a9f56e8e
Create Date: 2024-10-01 05:54:03.673256

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '55cd88f727e3'
down_revision = '84f3a9f56e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('img', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'img')
    op.drop_column('item', 'supplier')
    # ### end Alembic commands ###
