"""Employee relation is added

Revision ID: 6c973b036011
Revises: f77791a0285a
Create Date: 2024-09-23 12:10:35.982655

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c973b036011'
down_revision = 'f77791a0285a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
