"""Address model added and Sales model refatored

Revision ID: 7a349ec9e7bc
Revises: c5a85b8efadd
Create Date: 2024-10-08 06:18:09.969525

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7a349ec9e7bc'
down_revision = 'c5a85b8efadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('billing_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('billing_city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('billing_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('billing_country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('billing_zip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('shipping_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('shipping_city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('shipping_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('shipping_country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('shipping_zip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('receiver_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('receiver_phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('receiver_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('sale', 'shipping_state')
    op.drop_column('sale', 'billing_city')
    op.drop_column('sale', 'shipping_city')
    op.drop_column('sale', 'billing_state')
    op.drop_column('sale', 'receiver_phone')
    op.drop_column('sale', 'shipping_country')
    op.drop_column('sale', 'receiver_email')
    op.drop_column('sale', 'shipping_zip')
    op.drop_column('sale', 'shipping_address')
    op.drop_column('sale', 'receiver_name')
    op.drop_column('sale', 'billing_zip')
    op.drop_column('sale', 'billing_country')
    op.drop_column('sale', 'billing_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('billing_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sale', sa.Column('billing_country', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sale', sa.Column('billing_zip', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sale', sa.Column('receiver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sale', sa.Column('shipping_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sale', sa.Column('shipping_zip', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sale', sa.Column('receiver_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sale', sa.Column('shipping_country', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sale', sa.Column('receiver_phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sale', sa.Column('billing_state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sale', sa.Column('shipping_city', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sale', sa.Column('billing_city', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sale', sa.Column('shipping_state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('address')
    # ### end Alembic commands ###
