"""Item business_id refactor

Revision ID: 84f3a9f56e8e
Revises: a02bcce488b7
Create Date: 2024-09-30 09:14:12.480846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '84f3a9f56e8e'
down_revision = 'a02bcce488b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('business_id', sa.Uuid(), nullable=False))
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'business', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'business_id')
    # ### end Alembic commands ###
