"""Add validation default to product_group_model

Revision ID: a02bcce488b7
Revises: debdd1c62620
Create Date: 2024-09-30 07:29:34.758480

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a02bcce488b7'
down_revision = 'debdd1c62620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
