"""product model update

Revision ID: ad3ff4bb666a
Revises: 422d5b10b456
Create Date: 2024-09-25 10:03:45.000432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ad3ff4bb666a'
down_revision = '422d5b10b456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('product', sa.Column('moderated', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('product_group_id', sa.Uuid(), nullable=False))
    op.drop_constraint('product_product_group_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'productgroup', ['product_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product', 'product_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_group', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_product_group_fkey', 'product', 'productgroup', ['product_group'], ['id'], ondelete='CASCADE')
    op.drop_column('product', 'product_group_id')
    op.drop_column('product', 'moderated')
    op.alter_column('employee', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
