"""Item add quantity

Revision ID: c5a85b8efadd
Revises: 55cd88f727e3
Create Date: 2024-10-01 12:51:59.928385

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5a85b8efadd'
down_revision = '55cd88f727e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'quantity')
    # ### end Alembic commands ###
