"""Sale field rename

Revision ID: cca74d05ba60
Revises: 7a349ec9e7bc
Create Date: 2024-10-08 06:23:55.603681

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cca74d05ba60'
down_revision = '7a349ec9e7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('price_per_item', sa.Float(), nullable=False))
    op.drop_column('sale', 'total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('sale', 'price_per_item')
    # ### end Alembic commands ###
