"""Add validation to product_group_model

Revision ID: debdd1c62620
Revises: 7122b20a3a9a
Create Date: 2024-09-30 07:25:56.173390

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'debdd1c62620'
down_revision = '7122b20a3a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productgroup', sa.Column('validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productgroup', 'validated')
    # ### end Alembic commands ###
